[gui.profile]
title = "<red>Profil"
achievements = "Coming Soon"
next.lore = "<yellow>zu Season <season>"
previous.lore = "<yellow>zu Season <season>"
head.lore = """
    <rank><reset>
    <br><level><reset> 
"""
season = "<gray>Season</gray><dark_gray>:</dark_gray> <yellow><season>"
loadingSeason = "<gray>Lade Season</gray><dark_gray>:</dark_gray> <yellow><season>"

globalItem = """
    <gray>Platz<dark_gray>: <elorank>
    <br><gray>ğŸ†<dark_gray>: <elo>
    <br><gray>HÃ¶chste ğŸ†<dark_gray>: <topelo>
    <br>
    <br><gray>Gespielte Spiele<dark_gray>: <yellow><gamesplayed>
    <br><gray>Gewonnene Spiele<dark_gray>: <yellow><gameswon>
    <br>
    <br><gray>Winstreak<dark_gray>: <yellow><winstreak>
    <br><gray>HÃ¶chste Winstreak<dark_gray>: <yellow><topwinstreak>
    <br>
    <br><gray>Spielzeit<dark_gray>: <yellow><playtime>
"""

kitItem = """
    <gray>Platz<dark_gray>: <elorank>
    <br><gray>ğŸ†<dark_gray>: <elo>
    <br><gray>HÃ¶chste ğŸ†<dark_gray>: <topelo>
    <br>
    <br><gray>Gespielte Spiele<dark_gray>: <yellow><gamesplayed>
    <br><gray>Gewonnene Spiele<dark_gray>: <yellow><gameswon>
    <br>
    <br><gray>Winstreak<dark_gray>: <yellow><winstreak>
    <br><gray>HÃ¶chste Winstreak<dark_gray>: <yellow><topwinstreak>
"""
